### ISSUE TITLE
Feature: Top Performing Crypto Data

### ISSUE THREAD

**Issue by Jensen098** [Jensen098/flutter_crypto_wallet#1]
# Epic Title

Feature: Top Performing Crypto Data

## Epic Description

This Feature will fetch data on the top performing crypto currencies, using an API, and display information such as icons, price and growth to the user as well as providing a general overview of the currency. User's will then be able to filter market price based on history (i.e. 24hr, 1w, 1y, etc.). 

## List of Tasks

1. [X] [Task 3: Create Currency Mock Data](https://github.com/Jensen098/flutter_crypto_wallet/issues/3)
2. [X] [Task 6: Create History Mock Data](https://github.com/Jensen098/flutter_crypto_wallet/issues/6)
3. [ ] [Task 7: Select Chart Package for Flutter](https://github.com/Jensen098/flutter_crypto_wallet/issues/7)
4. [X] [Task 8: Select Crypto Currency API](https://github.com/Jensen098/flutter_crypto_wallet/issues/8)
5. [X] [Task 9: Build Home Screen Currency List](https://github.com/Jensen098/flutter_crypto_wallet/issues/9)
6. [ ] [Task 10: Build Coin History Screen](https://github.com/Jensen098/flutter_crypto_wallet/issues/10)

## Screenshots

![Crypto App v1](https://user-images.githubusercontent.com/27798623/117113164-6f2c3080-adcd-11eb-9948-8452664d0875.png)
