### ISSUE TITLE
Feature: Crypto Currency Wallet

### ISSUE THREAD

**Issue by Jensen098** [Jensen098/flutter_crypto_wallet#2]
# Epic Title

Feature: Crypto Currency Wallet

## Epic Description

This Feature will allow user's to view crypto their currency assets, such as amount invested and total number of coins, so that they can see real-time value of their assets. User's should be able to add, edit, and remove coins.

## List of Tasks

1. [ ] [Task 11: Create Wallet Mock Data](https://github.com/Jensen098/flutter_crypto_wallet/issues/11)
2. [ ] [Task 12: Build User Profile Screen](https://github.com/username/repository-name/issues/12)
3. [ ] [Task 13: Add Asset to Crypto Wallet](https://github.com/Jensen098/flutter_crypto_wallet/issues/13)
4. [ ] [Task 14: Edit Asset in Crypto Wallet](https://github.com/Jensen098/flutter_crypto_wallet/issues/14)
5. [ ] [Task 15: Remove Asset in Crypto Wallet](https://github.com/Jensen098/flutter_crypto_wallet/issues/15)
6. [ ] [Task 16: Build Home Screen Crypto Wallet](https://github.com/Jensen098/flutter_crypto_wallet/issues/16)

## Screenshots

![Crypto App v1](https://user-images.githubusercontent.com/27798623/117113164-6f2c3080-adcd-11eb-9948-8452664d0875.png)
